name: Quick Build (Current Platform)

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build for"
        required: true
        default: "current"
        type: choice
        options:
          - current
          - macos-intel
          - macos-m1
          - windows
          - linux

jobs:
  quick-build:
    runs-on: >-
      ${{
        inputs.platform == 'windows' && 'windows-latest' ||
        (inputs.platform == 'macos-intel' || inputs.platform == 'macos-m1') && 'macos-latest' ||
        inputs.platform == 'linux' && 'ubuntu-22.04' ||
        'ubuntu-22.04'
      }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev libayatana-appindicator3-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: >-
            ${{
              inputs.platform == 'macos-intel' && 'x86_64-apple-darwin' ||
              inputs.platform == 'macos-m1' && 'aarch64-apple-darwin' ||
              inputs.platform == 'windows' && 'x86_64-pc-windows-msvc' ||
              inputs.platform == 'linux' && 'x86_64-unknown-linux-gnu' ||
              ''
            }}

      - name: Build frontend
        run: pnpm build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            ${{
              inputs.platform == 'macos-intel' && '--target x86_64-apple-darwin' ||
              inputs.platform == 'macos-m1' && '--target aarch64-apple-darwin' ||
              inputs.platform == 'windows' && '--target x86_64-pc-windows-msvc' ||
              inputs.platform == 'linux' && '--target x86_64-unknown-linux-gnu' ||
              ''
            }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: auto-cursor-quick-build-${{ inputs.platform }}
          path: src-tauri/target/*/release/bundle/**/*
          if-no-files-found: warn
